version: '3'

services:
  nestjs:
    build:
      context: ../sample-be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  vuejs:
    build:
      context: ../sample-fe
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge